import type { Metadata } from "next";
import "@/font/iranSans.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className="font-iransans bg-slate-300">{children}</body>
    </html>
  );
}
